language: php

php:
  - "5.6"
  - "hhvm"
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database maoni_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --database test

services:
  - mysql

script:
- vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
#  fast_finish: false

# Customize when the notification emails are sent.
#notifications:
#    on_success: never
#    on_failure: always